# Generated by Django 5.2.6 on 2025-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='from_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_new_message',
            field=models.BooleanField(default=False),
        ),
    ]
